apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      imagePullSecrets:
        - name: harbor-registry

      containers:
        - name: demo-app
          image: harbor.kubeops.local/kubeops/demo-app:32

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
